spring.application.name=unitTestDemo

# H2 in-memory
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

# Hibernate auto-create tables
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Optional: ensure Spring runs preloading scripts after table creation
spring.sql.init.mode=never